// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Samples.InfrastructureLayer.DataContext;
using System;

namespace Samples.InfrastructureLayer.DataContext.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20171120191408_Organization")]
    partial class Organization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Samples.InfrastructureLayer.OrganizationDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Samples.InfrastructureLayer.OrganizationPersonDao", b =>
                {
                    b.Property<Guid>("PersonId");

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("PersonId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationPersons");
                });

            modelBuilder.Entity("Samples.InfrastructureLayer.Persons.PersonDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<int>("LastFourDigits");

                    b.Property<string>("LastName");

                    b.Property<string>("MailAddress");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Samples.InfrastructureLayer.OrganizationPersonDao", b =>
                {
                    b.HasOne("Samples.InfrastructureLayer.OrganizationDao", "Organization")
                        .WithMany("OrganizationPersons")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Samples.InfrastructureLayer.Persons.PersonDao", "Person")
                        .WithMany("OrganizationPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
